src/main/java/eng/valdinilson/loucademia/domain/acesso/Acesso.java
package eng.valdinilson.loucademia.domain.acesso;

import eng.valdinilson.loucademia.domain.aluno.Aluno;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;

@Entity
@Table(name = "ENTRADAS_SAIDAS")
@Getter
@Setter
@EqualsAndHashCode
@ToString
public class Acesso implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false)
    private Integer id;
    @ManyToOne
    @JoinColumn(name = "ALUNO_ID", nullable = false)
    private Aluno aluno;
    @Column(name = "ENTRADA", nullable = false)
    private LocalDateTime entrada;
    @Column(name = "SAIDA")
    private LocalDateTime saida;
}

src/main/java/eng/valdinilson/loucademia/domain/aluno/Aluno.java
package eng.valdinilson.loucademia.domain.aluno;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.apache.commons.lang3.StringUtils;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.Year;

@Entity
@Table(name = "ALUNO")
@Getter
@Setter
@EqualsAndHashCode
@ToString
public class Aluno implements Serializable {
    public enum Sexo {
        MASCULINO, FEMININO;
    }

    public enum Situacao {
        ATIVO, INATIVO, PENDENTE;
    }

    @Id
    @Column(name = "ID", nullable = false, length = 8)
    private String matricula;
    @Column(name = "NOME", nullable = false, length = 64)
    private String nome;
    @Enumerated
    @Column(name = "SEXO", nullable = false, length = 1)
    private Sexo sexo;
    @Column(name = "RG", nullable = false, length = 10)
    private Integer rg;
    @Column(name = "NASCIMENTO", nullable = false)
    private LocalDate dataNascimento;
    @Enumerated
    @Column(name = "SITUACAO", nullable = false, length = 1)
    private Situacao situacao;
    @Column(name = "EMAIL", length = 64)
    private String email;
    @Embedded
    private Endereco endereco = new Endereco();
    @Embedded
    private Telefone telefone = new Telefone();

    public void gerarMatricula(String maxMatricula) {
        Year year = Year.now();

        if (maxMatricula == null) {
            maxMatricula =  year + StringUtils.leftPad("", 4, "0");
        }

        int sequential = Integer.parseInt(maxMatricula.substring(4));
        sequential++;

        this.matricula = year + StringUtils.leftPad(String.valueOf(sequential), 4, "0");
    }
}

src/main/java/eng/valdinilson/loucademia/domain/aluno/Endereco.java
package eng.valdinilson.loucademia.domain.aluno;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import java.io.Serializable;

@Embeddable
@Getter
@Setter
@EqualsAndHashCode
@ToString
public class Endereco implements Serializable {
    @Column(name = "RUA", nullable = false, length = 128)
    private String rua;
    @Column(name = "NUMERO", length = 6)
    private Integer numero;
    @Column(name = "COMPLEMENTO", length = 32)
    private String complemento;
    @Column(name = "CIDADE", nullable = false, length = 64)
    private String cidade;
    @ManyToOne
    @JoinColumn(name = "ESTADO_ID", nullable = false)
    private Estado estado = new Estado();
    @Column(name = "CEP", nullable = false, length = 8)
    private Integer cep;
}

src/main/java/eng/valdinilson/loucademia/domain/aluno/Estado.java
package eng.valdinilson.loucademia.domain.aluno;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Entity
@Table(name = "ESTADO")
@Getter
@Setter
@EqualsAndHashCode
@ToString
public class Estado implements Serializable {
    @Id
    @Column(name = "SIGLA", nullable = false, length = 2)
    private String sigla;
    @Column(name = "NOME", nullable = false, length = 30)
    private String nome;
}

src/main/java/eng/valdinilson/loucademia/domain/aluno/Telefone.java
package eng.valdinilson.loucademia.domain.aluno;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.io.Serializable;

@Embeddable
@Getter
@Setter
@EqualsAndHashCode
@ToString
public class Telefone implements Serializable {
    @Column(name = "CELULAR_DDD", nullable = false, length = 2)
    private Integer dddCelular;
    @Column(name = "CELULAR_NUMERO", nullable = false, length = 9)
    private Integer numeroCelular;
    @Column(name = "FIXO_DDD", length = 2)
    private Integer dddFixo;
    @Column(name = "FIXO_NUMERO", length = 8)
    private Integer numeroFixo;
}

src/main/java/eng/valdinilson/loucademia/interfaces/aluno/AlunoBean.java
package eng.valdinilson.loucademia.interfaces.aluno;

import eng.valdinilson.loucademia.application.service.AlunoService;
import eng.valdinilson.loucademia.domain.aluno.Aluno;
import lombok.Getter;
import lombok.Setter;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import java.io.Serializable;

@Named
@RequestScoped
@Getter
@Setter
public class AlunoBean implements Serializable {
    @EJB
    private AlunoService alunoService;
    private Aluno aluno = new Aluno();

    public String gravar() {
        alunoService.createOrUpdate(aluno);
        return null;
    }

    public void carregar() {
        //
    }

    public String getTitulo() {
        return getClass().getSimpleName();
    }
}

src/main/java/eng/valdinilson/loucademia/interfaces/shared/DataBean.java
package eng.valdinilson.loucademia.interfaces.shared;

import eng.valdinilson.loucademia.application.service.DataService;
import eng.valdinilson.loucademia.domain.aluno.Aluno;
import eng.valdinilson.loucademia.domain.aluno.Estado;

import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

@Named
@ApplicationScoped
public class DataBean implements Serializable {
    @EJB
    private DataService dataService;

    public Aluno.Sexo[] getSexos() {
        return dataService.getSexos();
    }

    public Aluno.Situacao[] getSituacoes() {
        return dataService.getSituacoes();
    }

    public List<Estado> getEstados() {
        return dataService.listEstados();
    }
}

src/main/webapp/bemVindo.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	  xmlns:f="http://xmlns.jcp.org/jsf/core"
	  xmlns:jsf="http://xmlns.jcp.org/jsf"
	  lang="pt-br">
	
	<ui:composition template="layout.xhtml">
		<ui:param name="title" value="Bem Vindo!" />
		<ui:define name="conteudo">
		</ui:define>
	</ui:composition>
</html>

src/main/webapp/controleDeAcesso.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	  xmlns:f="http://xmlns.jcp.org/jsf/core"
	  xmlns:jsf="http://xmlns.jcp.org/jsf"
	  lang="pt-br">
	
	<ui:composition template="layout.xhtml">
		<ui:param name="title" value="Controle de Acesso" />
		<ui:define name="conteudo">
			<form jsf:id="form">
				<fieldset>
					<legend>Parâmetros da Acesso</legend>
					<label for="id">Matrícula</label><br />
					<input type="text" jsf:value="#{controleAcessoBean.matricula}" id="id" jsf:label="Matrícula" /><br />
					<label for="rg">RG</label><br />
					<input type="text" jsf:value="#{controleAcessoBean.rg}" id="rg" jsf:label="RG" /><br />
				</fieldset>
				
				<br />
				
				<input type="submit" value="Registrar acesso" jsf:action="#{controleAcessoBean.registrarAcesso}" />
			</form>
		</ui:define>
	</ui:composition>
</html>

src/main/webapp/dadosAluno.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	  xmlns:f="http://xmlns.jcp.org/jsf/core"
	  xmlns:jsf="http://xmlns.jcp.org/jsf"
	  lang="pt-br">
	
	<ui:composition template="layout.xhtml">
		<ui:param name="title" value="#{alunoBean.titulo}" />
		<f:metadata>
			<f:viewParam name="matricula" value="#{alunoBean.aluno.matricula}" />
			<f:viewAction action="#{alunoBean.carregar}" />
		</f:metadata>
		<ui:define name="conteudo">
			<form jsf:id="form">
				<input type="hidden" jsf:value="#{alunoBean.aluno.matricula}" />
				
				<fieldset>
					<legend>Dados pessoais</legend>
					<label for="nome">Nome</label><br />
					<input type="text" jsf:value="#{alunoBean.aluno.nome}" id="nome" maxlength="64" jsf:label="Nome">
						<f:validateLength minimum="2" maximum="64" />
					</input><br />
					<label for="sexo">Sexo</label><br />
					<select jsf:value="#{alunoBean.aluno.sexo}" id="sexo" size="0">
						<f:selectItems value="#{dataBean.sexos}" />
					</select><br />
					<label for="rg">RG</label><br />
					<input type="text" jsf:value="#{alunoBean.aluno.rg}" id="rg" maxlength="10" jsf:label="RG">
						<f:validateRequired />
						<f:validateLongRange minimum="100000" maximum="9999999999" />
					</input><br />
					<label for="dataDeNascimento">Data de Nascimento</label><br />
					<input type="date" jsf:value="#{alunoBean.aluno.dataNascimento}" id="dataDeNascimento" jsf:label="Data de Nascimento">
						<f:convertDateTime type="localDate" pattern="yyyy-MM-dd" />
						<f:validateRequired />
					</input>
				</fieldset>
			
				<br />
				
				<fieldset>
					<legend>Situação</legend>
					<label for="situacao">Situação</label><br />
					<select jsf:value="#{alunoBean.aluno.situacao}" id="situacao" size="0">
						<f:selectItems value="#{dataBean.situacoes}" />
					</select>
				</fieldset>
				
				<br />
				
				<fieldset>
					<legend>Endereço</legend>
					<label for="rua">Rua</label><br />
					<input type="text" jsf:value="#{alunoBean.aluno.endereco.rua}" id="rua" maxlength="128" jsf:label="Rua">
						<f:validateLength minimum="2" maximum="128" />
					</input><br />
					
					<label for="numero">Número</label><br />
					<input type="text" jsf:value="#{alunoBean.aluno.endereco.numero}" id="numero" maxlength="6" jsf:label="Nï¿½mero">
						<f:validateLongRange minimum="1" maximum="999999" />
					</input><br />
					
					<label for="complemento">Complemento</label><br />
					<input type="text" jsf:value="#{alunoBean.aluno.endereco.complemento}" id="complemento" maxlength="32" jsf:label="Complemento">
						<f:validateLength maximum="32" />
					</input><br />
					
					<label for="cidade">Cidade</label><br />
					<input type="text" jsf:value="#{alunoBean.aluno.endereco.cidade}" id="cidade" maxlength="64" jsf:label="Cidade">
						<f:validateLength minimum="2" maximum="64" />
					</input><br />
					
					<label for="estado">Estado</label><br />
					<select jsf:value="#{alunoBean.aluno.endereco.estado.sigla}" id="estado" size="0" jsf:label="Estado">
						<f:selectItem itemLabel="Escolha..." itemValue="" />
						<f:selectItems value="#{dataBean.estados}" var="e" itemLabel="#{e.nome}" itemValue="#{e.sigla}" />
						<f:validateRequired />
					</select><br />
					
					<label for="cep">CEP</label><br />
					<input type="text" jsf:value="${alunoBean.aluno.endereco.cep}" id="cep" maxlength="8" jsf:label="CEP">
						<f:validateRequired />
						<f:validateLongRange minimum="10000000" maximum="99999999" />
					</input>
				</fieldset>
				
				<br />
				
				<fieldset>
					<legend>Contato</legend>
					<label for="email">E-mail</label><br />
					<input type="email" jsf:value="#{alunoBean.aluno.email}" id="email" maxlength="64" jsf:label="E-mail">
						<f:validateLength maximum="64" />
						<f:validateRegex pattern=".+@.+" />
					</input><br />
					
					<label for="telefoneCelularDDD">Telefone Celular</label><br />
					<input type="tel" jsf:value="#{alunoBean.aluno.telefone.dddCelular}" id="telefoneCelularDDD" maxlength="2" jsf:label="DDD celular">
						<f:validateRequired />
						<f:validateLongRange minimum="10" maximum="99" />
					</input>&#160;
					<input type="tel" jsf:value="#{alunoBean.aluno.telefone.numeroCelular}" id="telefoneCelularNumero" maxlength="9" jsf:label="Telefone celular">
						<f:validateRequired />
						<f:validateLongRange minimum="10000000" maximum="999999999" />
					</input><br />
					
					<label for="telefoneFixoDDD">Telefone Fixo</label><br />
					<input type="tel" jsf:value="#{alunoBean.aluno.telefone.dddFixo}" id="telefoneFixoDDD" maxlength="2" jsf:label="DDD fixo">
						<f:validateLongRange minimum="10" maximum="99" />
					</input>&#160;
					<input type="tel" jsf:value="#{alunoBean.aluno.telefone.numeroFixo}" id="telefoneFixoNumero" maxlength="9" jsf:label="Telefone fixo">
						<f:validateLongRange minimum="10000000" maximum="999999999" />
					</input>
				</fieldset>
			
				<br />
				
				<input type="submit" value="Gravar" jsf:action="#{alunoBean.gravar}" />&#160;
				<input type="button" value="Relatório de Entradas e Saídas"
					jsf:outcome="relatoriosDeEntradaSaida?matricula=#{alunoBean.aluno.matricula}"
					jsf:rendered="#{alunoBean.aluno.matricula != null}" />
	
			</form>
		</ui:define>
	</ui:composition>
</html>

src/main/webapp/layout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	  xmlns:f="http://xmlns.jcp.org/jsf/core"
	  xmlns:jsf="http://xmlns.jcp.org/jsf"
	  lang="pt-br">
	<head jsf:id="head">
		<meta charset="UTF-8" />
		<title>Loucademia</title>
		<link rel="stylesheet" type="text/css" href="css/Loucademia_Estilo.css" />
	</head>
	<body>
		<!--  Cabeçalho - Início -->
		<header>
			<img src="images/Loucademia_Logotipo.png" />
			<nav>
				<div>
					<a jsf:outcome="dadosAluno">Novo aluno</a><br />
					<a jsf:outcome="pesquisaDeAluno?clear=true">Pesquisa de aluno</a><br />
					<a jsf:outcome="controleDeAcesso">Controle de acesso</a><br />
					<a jsf:outcome="relatoriosDeEntradaSaida">Relatórios de Entradas e Saídas</a><br />
					<a jsf:outcome="relatoriosDeSituacoes?clear=true">Relatórios de Situações</a><br />
				</div>
			</nav>
		</header>
		
		<h1>#{title}</h1>
			
		<h:panelGroup rendered="#{!facesContext.messageList.isEmpty()}">
			<div id="infoMessage">
				<h:messages />
			</div>
		</h:panelGroup>
		
		<br />
		<!--  Cabeçalho - Fim -->
		
		<ui:insert name="conteudo" />
	</body>
</html>

src/main/webapp/pesquisaDeAluno.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	lang="pt-br">
	
	<ui:composition template="layout.xhtml">
	<ui:param name="title" value="Pesquisa de aluno" />
		<ui:define name="conteudo">
			<f:metadata>
				<f:viewAction action="#{pesquisaAlunoBean.check}" />
			</f:metadata>
			
			<form jsf:id="form">
				<fieldset>
					<legend>Parâmetros da Pesquisa</legend>
					<label for="id">Matrícula</label><br />
					<input type="text" jsf:value="#{pesquisaAlunoBean.matricula}" id="id" jsf:label="Matrícula" /><br />
					<label for="nome">Nome</label><br />
					<input type="text" jsf:value="#{pesquisaAlunoBean.nome}" id="nome" jsf:label="Nome" /><br />
					<label for="rg">RG</label><br />
					<input type="text" jsf:value="#{pesquisaAlunoBean.rg}" id="rg" jsf:label="RG" /><br />
					<label for="telefoneDDD">Telefone</label><br />
					<input type="tel" jsf:value="#{pesquisaAlunoBean.telefone}" id="telefoneNumero" jsf:label="Telefone" />
				</fieldset>
				
				<br />
				
				<input type="submit" value="Pesquisar" jsf:action="#{pesquisaAlunoBean.pesquisar}" />
			
				<h:panelGroup rendered="#{not empty pesquisaAlunoBean.alunos}">
					<table>
						<tr>
							<th>Matrícula</th>
							<th>Nome</th>
							<th>RG</th>
							<th>E-mail</th>
							<th>Telefone</th>
							<th>Situação</th>
							<th>Ações</th>
						</tr>
						<ui:repeat var="a" value="#{pesquisaAlunoBean.alunos}">
							<tr>
								<td>#{a.matricula}</td>
								<td>#{a.nome}</td>
								<td>#{a.rg}</td>
								<td>#{a.email}</td>
								<td>
									#{dataBean.formatTelefone(a.telefone.dddCelular, a.telefone.numeroCelular)}<br />
									#{dataBean.formatTelefone(a.telefone.dddFixo, a.telefone.numeroFixo)}
								</td>
								<td>#{a.situacao}</td>
								<td>
									<input type="button" value="Editar" jsf:outcome="dadosAluno?matricula=#{a.matricula}" />&#160;
									<input type="submit" value="Excluir" onclick="return confirm('Deseja excluir o aluno #{a.matricula}?');" jsf:action="#{pesquisaAlunoBean.excluir(a.matricula)}" />
								</td>
							</tr>
						</ui:repeat>
					</table>
				</h:panelGroup>
			</form>
		</ui:define>
	</ui:composition>
</html>

src/main/webapp/relatoriosDeEntradaSaida.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	lang="pt-br">
	
	<ui:composition template="layout.xhtml">
		<ui:param name="title" value="Relatórios de Entradas e Saídas" />
		<ui:define name="conteudo">
			<f:metadata>
				<f:viewParam name="matricula" value="#{relatorioEntradaSaidaBean.matricula}" />
				<f:viewAction action="#{relatorioEntradaSaidaBean.carregarAluno}" />
			</f:metadata>

			<form jsf:id="form">
				<fieldset>
					<legend>Parâmetros de Entradas e Saídas</legend>
					<label for="id">Matrícula</label><br />
					<input type="text" jsf:value="#{relatorioEntradaSaidaBean.matricula}" id="id" /><br />
					<label for="dataInicial">Data Inicial</label><br />
					<input type="date" jsf:value="#{relatorioEntradaSaidaBean.dataInicial}" id="dataInicial">
						<f:convertDateTime type="localDate" pattern="yyyy-MM-dd" />
					</input><br />
					<label for="dataFinal">Data Final</label><br />
					<input type="date" jsf:value="#{relatorioEntradaSaidaBean.dataFinal}" id="dataFinal">
						<f:convertDateTime type="localDate" pattern="yyyy-MM-dd" />
					</input>
				</fieldset>
				
				<br />
				
				<input type="submit" value="Gerar relatório" jsf:action="#{relatorioEntradaSaidaBean.gerarRelatorio}" />

				<h:panelGroup rendered="#{not empty relatorioEntradaSaidaBean.acessos}">
					<table>
						<tr>
							<th>Matrícula</th>
							<th>Nome</th>
							<th>Entrada</th>
							<th>Saída</th>
							<th>Duração</th>
						</tr>
						<ui:repeat var="a" value="#{relatorioEntradaSaidaBean.acessos}">
							<tr>
								<td>#{a.aluno.matricula}</td>
								<td>#{a.aluno.nome}</td>
								<td>
									<h:outputText value="#{a.entrada}">
										<f:convertDateTime type="localDateTime" pattern="dd/MM/yyyy HH:mm" />
									</h:outputText>
								</td>
								<td>
									<h:outputText value="#{a.saida}">
										<f:convertDateTime type="localDateTime" pattern="dd/MM/yyyy HH:mm" />
									</h:outputText>
								</td>
								<td>#{a.calcularDuracao()}</td>
							</tr>
						</ui:repeat>
					</table>
				</h:panelGroup>
			</form>
		</ui:define>
	</ui:composition>
</html>